# Generated by Django 5.2.8 on 2025-12-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_artist_artstation_artist_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='art_type',
            field=models.CharField(choices=[('classical', 'Классическая живопись'), ('modern', 'Современное искусство'), ('digital', 'Цифровое искусство'), ('other', 'Другое')], default='classical', max_length=20, verbose_name='Тип искусства'),
        ),
    ]
