# Generated by Django 5.2.8 on 2025-12-26 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_painting_art_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paintinglike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='paintinglike',
            name='painting',
        ),
        migrations.RemoveField(
            model_name='paintinglike',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='userpreference',
            options={'verbose_name': 'Предпочтения пользователя', 'verbose_name_plural': 'Предпочтения пользователей'},
        ),
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='painting',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_paintings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='favorite_artists',
            field=models.ManyToManyField(blank=True, to='gallery.artist', verbose_name='Любимые художники'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='favorite_genres',
            field=models.ManyToManyField(blank=True, to='gallery.genre', verbose_name='Любимые жанры'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('favorite_paintings', models.ManyToManyField(blank=True, related_name='favorited_by', to='gallery.painting', verbose_name='Избранные картины')),
                ('following_artists', models.ManyToManyField(blank=True, related_name='followers', to='gallery.artist', verbose_name='Подписки на художников')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.DeleteModel(
            name='ArtistLike',
        ),
        migrations.DeleteModel(
            name='PaintingLike',
        ),
    ]
